### ISSUE TITLE
Issue with "images"

### ISSUE THREAD

**Issue by gtam-deloitte** [PaloAltoNetworks/prisma.pan.dev#252]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

TypeError: this.description.search is not a function
    at new mn (https://prisma.pan.dev/assets/js/common.f1a889d2.js:41:17055)
    at new Zr (https://prisma.pan.dev/assets/js/common.f1a889d2.js:41:40402)
    at new il (https://prisma.pan.dev/assets/js/common.f1a889d2.js:1217:2803)
    at https://prisma.pan.dev/assets/js/common.f1a889d2.js:118:539
    at Object.Ti [as useMemo] (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:392249)
    at t.useMemo (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:477214)
    at $i (https://prisma.pan.dev/assets/js/common.f1a889d2.js:118:496)
    at li (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:387545)
    at Hi (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:397063)
    at Yc (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:440597)

**Comment by csestito** [comment]
This has been fixed. Please let us know if you see the issue again.
