### ISSUE TITLE
Issue with "policies" in 22_06 docs

### ISSUE THREAD

**Issue by pan0ptic0n** [PaloAltoNetworks/prisma.pan.dev#253]
## Error in Container Policy (and probably other) Docs

https://prisma.pan.dev/api/cloud/cwpp/policies#operation/get-policies-firewall-app-container

![Screen Shot 2022-08-26 at 10 30 25 AM](https://user-images.githubusercontent.com/101208806/186927448-7eb19c62-89e7-4c80-84d8-32b5796c41bf.png)

Errors with server specifics and a Stack Trace.

 **A Stack Trace!!** We are a security company and this sort of information absolutely should not bleed.

```
TypeError: this.description.search is not a function
    at new mn (https://prisma.pan.dev/assets/js/common.f1a889d2.js:41:17055)
    at new Zr (https://prisma.pan.dev/assets/js/common.f1a889d2.js:41:40402)
    at new il (https://prisma.pan.dev/assets/js/common.f1a889d2.js:1217:2803)
    at https://prisma.pan.dev/assets/js/common.f1a889d2.js:118:539
    at Object.Ti [as useMemo] (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:392249)
    at t.useMemo (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:477214)
    at $i (https://prisma.pan.dev/assets/js/common.f1a889d2.js:118:496)
    at li (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:387545)
    at Hi (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:397063)
    at Yc (https://prisma.pan.dev/assets/js/main.03a4108b.js:2:440597)
```

## Suggested fix

1. Fix underlying problem
2. Obscure errors: do *not* offer a stack trace

**Comment by csestito** [comment]
This has been fixed. Please let us know if you see the issue again.
